services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - REQUEST_ORIGIN=http://127.0.0.1:5000
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      - POSTGRES_USER=joshua
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=joshua
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080



  database:
    image: postgres:17
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=joshua
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=joshua 
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis:alpine


